name: mcDropShop
version: 0.1.0
description: Open source replacement for HoloShop - bukkit interactive holographic shops
author: majikchicken

main: io.github.casnix.mcdropshop.Main
depend: [HolographicDisplays, Vault]

commands:
  mcdropshop:
    description: Manage, create, and delete holoshops
